# Generated by Django 3.1 on 2021-02-15 23:43

import colorfield.fields
import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(default='', max_length=255)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='MacroProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_project_name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=500)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('manager', models.ManyToManyField(related_name='works_as_macroproject_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MacroProjects',
            },
        ),
        migrations.CreateModel(
            name='SamplesProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('place_name', models.CharField(default='Villa Clara', max_length=50)),
                ('local_site', models.CharField(default='', max_length=50)),
                ('Longitud_site', models.CharField(default='-80.22', max_length=50)),
                ('Latitud_site', models.CharField(default='22.58', max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('producer', models.CharField(default='Geocuba IC', max_length=50)),
                ('client', models.CharField(default='MINAG', max_length=50)),
                ('annotators', models.ManyToManyField(related_name='works_as_annotator', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='works_as_contact', to=settings.AUTH_USER_MODEL)),
                ('macro_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroproyect', to='data_annotator.macroproject')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_as_samplesproject_manager', to=settings.AUTH_USER_MODEL)),
                ('operators', models.ManyToManyField(related_name='works_as_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SamplesProjects',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_satellite', models.DateField(default=datetime.date(2020, 7, 16))),
                ('site_name', models.CharField(max_length=50)),
                ('label', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='site_label', to='data_annotator.label')),
                ('sample_project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='site_samplesproject', to='data_annotator.samplesproject')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'permissions': (('add_samples', 'delete_samples'),),
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_file', models.FileField(default=None, upload_to='temporal_files/')),
                ('description', models.TextField(default='', max_length=500)),
                ('sample_project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shape_samplesproject', to='data_annotator.samplesproject')),
            ],
            options={
                'verbose_name_plural': 'Shape',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_annotator', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('is_contact', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='macro_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_macroproject', to='data_annotator.macroproject'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(default=None, upload_to='temporal_files/')),
                ('platform', models.CharField(choices=[('1', 'Sentinel'), ('2', 'Drones'), ('3', 'Russia'), ('4', 'Landsat'), ('5', 'Spot')], max_length=200)),
                ('date_captured', models.DateField()),
                ('sample_project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_samplesproject', to='data_annotator.samplesproject')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
