# Generated by Django 3.1 on 2021-02-16 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_annotator', '0002_auto_20210216_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesproject',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
