# Generated by Django 3.1 on 2021-02-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotator', '0003_auto_20210216_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_proj',
            field=models.IntegerField(default=0),
        ),
    ]
