# Generated by Django 3.1 on 2021-03-10 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotator', '0006_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpa', models.CharField(default='', max_length=255)),
                ('fecha', models.DateField(default=datetime.date(2020, 12, 1))),
                ('bloque', models.IntegerField(default=0)),
                ('campo', models.IntegerField(default=0)),
                ('variedad', models.CharField(default='', max_length=255)),
                ('cepa', models.CharField(default='', max_length=255)),
                ('edad', models.FloatField(default=0.0)),
                ('pol_cana', models.FloatField(default=0.0)),
                ('pol_jugo', models.FloatField(default=0.0)),
                ('pureza', models.FloatField(default=0.0)),
                ('index', models.FloatField(default=0.0)),
                ('brix', models.FloatField(default=0.0)),
                ('brix_inf', models.FloatField(default=0.0)),
                ('brix_sup', models.FloatField(default=0.0)),
                ('im', models.FloatField(default=0.0)),
                ('fibra', models.FloatField(default=0.0)),
                ('rendimiento', models.FloatField(default=0.0)),
                ('ha', models.FloatField(default=0.0)),
                ('t_ha', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
            ],
        ),
    ]
