# Generated by Django 3.1 on 2021-03-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_annotator', '0007_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='sample_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='corte_samplesproject', to='data_annotator.samplesproject'),
        ),
    ]
